---

- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: install personal cask applications
      homebrew_cask: name={{item}} state=present
      with_items:
        - spotify
        - istat-menus
        - dropbox
        - kaleidoscope
        - hazel
        - sonos
        - tower
        - superduper
        - google-chrome
        - keepingyouawake
        - microsoft-office
        - atom
        - bartender
    - name: create ssh directory
      become: yes
      file:
        path: "{{item}}"
        state: directory
        owner: root
        group: wheel
        mode: 0777
      with_items:
        - /etc/ssh
    - name: add to sudoers without password
      become: yes
      lineinfile: >
        dest=/etc/sudoers
        regexp="{{ item.regexp }}"
        line="{{ item.line }}"
        state=present
        create=true
      with_items:
        - { regexp: '^roderik', line: 'roderik ALL=(ALL) NOPASSWD: ALL' }

  roles:
    - profile-all
    - profile-dev
    - profile-dev-python
    - profile-dev-golang
    - profile-dev-ruby
