---

- name: create ssh directory
  become: yes
  file:
    path: "{{item}}"
    state: directory
    owner: root
    group: wheel
    mode: 0777
  with_items:
    - /etc/ssh

- name: install general brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - wget
    - curl

- name: install general cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - google-chrome
    - firefox
    - box-sync
    - slack
    - evernote
    - xmind
    - the-unarchiver
    - appcleaner
    - caffeine
