---
galaxy_info:
  author: Patrick McClory
  description: Ansible profile role for developer workstations in general.
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - system
dependencies:
  - roderik.superlumic-sublimetext
  - roderik.superlumic-homebrew
