---

- name: Make go src directory
  file: path={{ home_dir }}/src/go state=directory

- name: Create .bash_profile if not exists
  command: "touch {{ home_dir }}/.bash_profile"
  args:
    creates: "{{ home_dir }}/.bash_profile"

- name: Set GOPATH
  lineinfile: dest={{ home_dir }}/.bash_profile line="export PATH=$PATH:{{ home_dir}}/src/go"

- name: Install golang
  homebrew: name={{item}} state=latest
  with_items:
    - go
    - gobject-introspection

- name: install Golang IDE cask applications
  homebrew_cask: name={{ item }} state=present
  with_items: "{{ install_ides }}"
