---

- name: install Python-speciic dev cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - python3
    - python

- name: install Python-speciic dev brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - pyenv-virtualenv
    - pyenv-virtualenvwrapper
    - pyenv-pip-migrate
