---

- name: install Python-speciic dev brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - python3
    - python
    - pyenv-virtualenv
    - pyenv-virtualenvwrapper
    - pyenv-pip-migrate
