---

- name: install rbenv
  git: repo=https://github.com/rbenv/rbenv.git dest=~/.rbenv

- name: install ruby-build as an rbenv plugin
  git: repo=https://github.com/rbenv/ruby-build.git dest=~/.rbenv/plugins/ruby-build

- name: install {{ rbenv.ruby_version }}
  shell: ~/.rbenv/bin/rbenv install --skip-existing {{ rbenv.ruby_version }}
  register: rbenv_install_result
  changed_when: "'' == rbenv_install_result.stdout"

- name: Create .bash_profile if not exists
  command: "touch {{ home_dir }}/.bash_profile"
  args:
    creates: "{{ home_dir }}/.bash_profile"

- name: add rbenv to path properly via .bash_profile
  become: yes
  lineinfile: >
    dest="{{home_dir}}/.bash_profile"
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
    create=true
  with_items:
    - { regexp: "^eval ", line: "eval \"$(rbenv init - )\"" }

- name: check if {{ rbenv.ruby_version }} is the default ruby version
  shell: ~/.rbenv/bin/rbenv global | grep -e '{{ rbenv.ruby_version }}'
  register: rbenv_check_default
  changed_when: False
  ignore_errors: True

- name: set default ruby version to {{ rbenv.ruby_version }}
  shell: ~/.rbenv/bin/rbenv global {{ rbenv.ruby_version }}
  when: rbenv_check_default|failed
