---

- name: install AWS-specific dev brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - wget
    - awscli

- name: install AWS-specific dev cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - python3
    - vagrant
    - virtualbox
    - python
    - packer
    - terraform
