---

- name: install AWS-specific dev brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - wget
    - awscli
    - python3
    - python
    - terraform
    - packer

- name: install AWS-specific dev cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - vagrant
    - virtualbox
