---

- name: install dev brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - git
    - git-extras
    - autoconf
    - automake
    - bash-completion
    - coreutils
    - htop-osx
    - netcat
    - nmap
    - tmux
    - jq

- name: install dev cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - dockertoolbox
    - atom
    - gpgtools
    - hosts
    - keybase
