---

- name: install dev brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - git
    - git-extras
    - autoconf
    - automake
    - bash-completion
    - docker-machine-driver-xhyve
    - coreutils
    - htop-osx
    - netcat
    - nmap
    - tmux
    - jq

- name: Download and place minikube in proper path
  get_url: url="https://storage.googleapis.com/minikube/releases/v{{ minikube_version }}/minikube-darwin-amd64" dest=/usr/local/bin/minikube mode=0755

- name: Download and place kubectl in proper path
  get_url: url="https://storage.googleapis.com/kubernetes-release/release/v{{ kubectl_version }}/bin/darwin/amd64/kubectl" dest=/usr/local/bin/kubectl mode=0755

- name: install dev cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - docker
    - atom
    - gpgtools
    - hosts
    - keybase
    - virtualbox
    - virtualbox-extension-pack
    - mou
